### ISSUE TITLE
New Layout for Bounty Details Screen

### ISSUE THREAD

**Issue by starpause** [HeroesHQ/HEROES#123]
## 🤼‍♂️  **What problem is your work solving.**

Build out the layout for the 'Bounty Details' screen as per the attached design. This screen is a part of the bounty creation flow and is critical for capturing the details of a bounty from the user. It's the first step of the bounty creation process.

## 🎉  **Describe the work you'd like**

![image](https://github.com/HeroesHQ/HEROES/assets/408953/80fb6632-89f8-4b9b-ab04-78d51fcc059e)

Layout Component Details: 

- [ ] "Create Bounty" Header (h1) 
- [ ] [Bounty Navigation Component](https://github.com/HeroesHQ/HEROES/issues/119)
- [ ] "Details" Header (h2)
- [ ] Title [Text input component](https://github.com/HeroesHQ/HEROES/issues/120)
  - Title: "Give your bounty a title"
  - Description: "Keep it short and simple."
  - Placeholder: "Website development..."
  - Required Field Indicator
  - Error text: "Required"
  - Learn More: "Some title examples"
- [ ] Description [Text input component](https://github.com/HeroesHQ/HEROES/issues/120)
  - Title: "What are you looking to get done?"
  - Description: "Provide Context, Work Deliverables, and Required Skills."
  - Placeholder: "I need..."
  - Required Field Indicator
  - Error text: "Required"
  - Learn More: "How to write a great description"
- [ ] [Tag input component](https://github.com/HeroesHQ/HEROES/issues/121)
  - Title: "Add Tags"
  - Description: "Make your bounty more visible to the right hunters."
- [ ] Specify deadline (progressive disclosure component)
  - Title: "Specify deadline" (visible by default)
  - Description: "After this date you cannot accept hunters or approve work. Detail time sensitive milestones above."
  - When checked the date select is made visible underneath the description. 
- [ ] Back / Next Buttons

## 🔗   Work doc(s) / inspirational links

[Designs](https://www.figma.com/file/kqZ5FzeLV1WBAERZCngbFC/Heroes?type=design&node-id=4378-7714&mode=design&t=B9FjIR9lQCbjuFXJ-0)
