### ISSUE TITLE
HEROES BOS WIDGET 1.0

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#47]
## 🎉   Subtasks

- [ ] Make sure to use standard near.org components to make frontend implementation easy (based on experince with newsletter widget), ask Denys about components to use if needed.

- [ ] Merge HEROES kanban BOS https://test.near.org/rostyksv2.testnet/widget/TabsWithItems widget with existing HEROES Widget on mainnet https://near.org/nearweekapp.near/widget/Heroes, so that it will be the same component and we only have one heroes widget on BOS.

- [ ] Remove "MY BOUNTIES" and "INVESTORS" tabs, instead replace with "KANBAN" view. The default page can be called "LIST" view

- [ ] Include filtering according to existing filtering system from heroes.build UI, so that as a user I can choose which bounties to view on the Kanban / list view

**Enhancement (unclear if this is possible on near.org)**

- [ ]  When a filter has been set, allow to make this to the specific URL (so that I can click https://near.org/nearweekapp.near/widget/Heroes/tags/nearweek forexample to see allow bounties tagged as nearweek

## 🤼‍♂️  Reviewer

@starpause @AngelBlock 

## 🔗   Work doc(s) / inspirational links

https://near.org/nearweekapp.near/widget/Heroes

https://test.near.org/rostyksv2.testnet/widget/TabsWithItems

**Comment by starpause** [comment]
Research the tag labeling system (change url for preset deep link, as we are doing on HEROES.BUILD)
