### ISSUE TITLE
UserName/ProfileHandler

### ISSUE THREAD

**Issue by Kisgus** [HeroesHQ/HEROES#56]
## 🎉   Subtasks

- [x] Rename "UserName/ProfileHandler" to "Username"
- [x] Rename "Name" to "Display Name"
- [ ] Ensure we reference "Display Name" in UI where ever we can.

- When going to detailed instead of "UserName/ProfileHandler" just switch to "Username" on profile Page <img width="1233" alt="Screenshot 2023-10-25 at 17 12 42" src="https://github.com/HeroesHQ/Kanban/assets/18598519/ed110feb-252c-45f6-a92d-bb1c7d32e068">

- When going to "Sign-up" switch "UserName/ProfileHandler" just switch to "Username"

<img width="566" alt="Screenshot 2023-10-25 at 17 17 45" src="https://github.com/HeroesHQ/Kanban/assets/18598519/b961aa56-8245-442c-ae6c-4e082fa441d8">

## 🤼‍♂️  Reviewer

@starpause

**Comment by AngelBlock** [comment]
![2023-11-22 15 23 16](https://github.com/HeroesHQ/HEROES/assets/80400686/6a162d24-931c-4950-a0fe-51309c768f2f)

Please change Display Name to **Full Name**
