### ISSUE TITLE
Bounty Poster Feedback

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [HeroesHQ/HEROES#99]
## 🎉   Subtasks

- [ ] Bounty taker is not able to edit deadline date once application for bounty is posted. Bounty poster cannot accept the bounty taker if there’s no deadline
![Screenshot 2023-08-31 at 13 51 04](https://github.com/HeroesHQ/Kanban/assets/89806831/5a22a8ee-413c-4762-85b4-1ea7f1dcbeb3)

**Solution:**
- we **WILL NOT** allow claiming with 0 deadline.

- [ ] A bounty requires my attention / action - it is not clear from UI that it is because I have applicants. 
Suggestion: add exclamation mark next to applicants. Also will I receive an email when I have applicants?
![Screenshot 2023-08-31 at 13 50 31](https://github.com/HeroesHQ/Kanban/assets/89806831/92f565b0-fbe8-4e95-9758-13240578445d)
![Screenshot 2023-08-31 at 13 50 45](https://github.com/HeroesHQ/Kanban/assets/89806831/5d8ab125-9fc5-4ae8-ac97-b4b7fd575315)

**Solution:**
- add exclamation to a particular applicant or all who responded.

- [ ] When bounty is completed as a user I would like to know that I’m looking at a completed bounty - I cannot tell from the current UI
![photo_2023-09-04 15 05 08](https://github.com/HeroesHQ/Kanban/assets/89806831/7027094f-dca2-4b0d-98b3-2f77fff9fdd5)
@maanemanden please provide the design.

- [ ] INVOICE” is found on the applicant page, not easy to discover, suggestion: put on the BOUNTY DETAILS page
![Screenshot 2023-08-31 at 14 24 07](https://github.com/HeroesHQ/Kanban/assets/89806831/90720169-fffa-4386-8dd4-abc32ffdf0f0)
@maanemanden 

- [ ] Ideally when bounty is completed I have all the information I need on the completed bounty page: Somewhere it needs to clearly state “COMPLETED” + Bounty taker and Invoice TAB could be in the blue area. The information in the red area confuses me as user --> As a user I want to know that the transaction was completed (mark w/ green) successfully and a hyperlink to the transaction
![Screenshot 2023-08-31 at 14 24 57](https://github.com/HeroesHQ/Kanban/assets/89806831/2ffaac4b-5057-4401-bc0e-f444166a0e2e)
@maanemanden 

- [x] CHECK YOUR PROOF OF PAYMENT HERE - "HERE" button has no functionality on HEROES platform, is only clickable when I download the invoice. There are 2 download signs on top of invoice
![Screenshot 2023-08-31 at 14 28 33](https://github.com/HeroesHQ/Kanban/assets/89806831/d7293b78-b1a1-45e8-9060-160c97d4b7ed)
**Solution:**
- this is by design, we skip this one for now

- [ ] What is required of bounty poster on the completed bounty applicants page? What does finalize mean? Why can I still accept or decline? Payment has been made to SOTA, I assume there are no more funds in the contract.
@maanemanden 

When payment has been performed as a user I would like to be asked whether the bounty should stay open or be closed - If closed all of the applicants should be notified that the bounty has been solved and is no longer live
@maanemanden 

![Screenshot 2023-08-31 at 14 32 05](https://github.com/HeroesHQ/Kanban/assets/89806831/460934bd-d06a-4bb9-8eed-2c46bac44f97)

## 🤼‍♂️  Reviewer

@AngelBlock

**Comment by Kisgus** [comment]
Hey @starpause @maanemanden please check if @P3ter-NEARWEEK feedback has been addressed
